/**
 * Core type definitions for Sah-AI.
 *
 * All types used across the safety pipeline, API routes, and UI.
 * This file has ZERO framework imports — it is pure TypeScript,
 * fully testable in isolation.
 *
 * @module types
 */

import { z } from "zod";

// ---------------------------------------------------------------------------
// Risk Classification
// ---------------------------------------------------------------------------

/**
 * Risk classification tags returned by the classifier.
 *
 * Safety invariant: on ANY ambiguous, unparseable, or error result,
 * the classifier defaults to "possible-overdose" (fail-closed).
 * See SAFETY.md §2.2 and ARD-003.
 */
export const RISK_TAGS = [
  "craving",
  "possible-overdose",
  "self-harm-risk",
  "education",
  "caregiver-request",
  "general",
] as const;

export type RiskTag = (typeof RISK_TAGS)[number];

/** Tags that trigger immediate bypass to static crisis content. */
export const CRISIS_TAGS: readonly RiskTag[] = [
  "possible-overdose",
  "self-harm-risk",
] as const;

/** The default (safest) tag used when classification fails. See ARD-003. */
export const FAIL_CLOSED_DEFAULT: RiskTag = "possible-overdose";

/**
 * Result of the risk classifier.
 */
export interface ClassifyResult {
  readonly tag: RiskTag;
  readonly confidence: number;
}

// ---------------------------------------------------------------------------
// Safety Filter
// ---------------------------------------------------------------------------

/**
 * Result of the deterministic safety filter.
 * When `safe` is false, `reason` explains why the content was rejected.
 */
export interface SafetyFilterResult {
  readonly safe: boolean;
  readonly reason?: string;
}

// ---------------------------------------------------------------------------
// Crisis Static Content
// ---------------------------------------------------------------------------

/**
 * A hotline action that can be rendered as a real `tel:` or `sms:` link.
 */
export interface HotlineAction {
  readonly type: "tel" | "sms";
  readonly number: string;
  readonly label: string;
}

/**
 * Pre-authored, clinician-reviewable crisis response content.
 * Served directly to the user — never generated by the LLM.
 * See SAFETY.md §2.1.
 */
export interface CrisisContent {
  readonly id: string;
  readonly title: string;
  readonly body: string;
  readonly actions: readonly HotlineAction[];
}

// ---------------------------------------------------------------------------
// Generated Scripts
// ---------------------------------------------------------------------------

/** User mode — Person in Recovery or Caregiver/Support Circle. */
export type UserMode = "pir" | "caregiver";

/** Tone control for generated scripts. */
export type ScriptTone = "gentle" | "direct" | "boundary-setting";

/**
 * A generated emergency/support script.
 * Always passes through the safety filter before reaching the client.
 */
export interface GeneratedScript {
  readonly scriptText: string;
  readonly tone: ScriptTone;
  readonly citationsUsed: string[];
}

// ---------------------------------------------------------------------------
// SAMHSA Treatment Locator
// ---------------------------------------------------------------------------

/**
 * A treatment facility returned by the SAMHSA locator.
 * Typed from the findtreatment.gov API response.
 */
export interface Facility {
  readonly name: string;
  readonly address: string;
  readonly city: string;
  readonly state: string;
  readonly zip: string;
  readonly phone: string;
  readonly website: string;
  readonly latitude: number | null;
  readonly longitude: number | null;
  readonly services: readonly string[];
  readonly payment: readonly string[];
  readonly specialPrograms: readonly string[];
  readonly languages: readonly string[];
  readonly facilityType: string;
}

// ---------------------------------------------------------------------------
// API Request/Response Schemas (Zod)
// ---------------------------------------------------------------------------

/**
 * Schema for the /api/classify request body.
 * Input is always re-validated server-side — never trust client input.
 */
export const ClassifyRequestSchema = z.object({
  input: z.string().min(1, "Input must not be empty"),
  sessionContext: z.string().optional(),
});
export type ClassifyRequest = z.infer<typeof ClassifyRequestSchema>;

/**
 * Schema for the /api/generate-script request body.
 */
export const GenerateScriptRequestSchema = z.object({
  mode: z.enum(["pir", "caregiver"]),
  context: z.string().min(1, "Context must not be empty"),
  tone: z.enum(["gentle", "direct", "boundary-setting"]).default("gentle"),
});
export type GenerateScriptRequest = z.infer<typeof GenerateScriptRequestSchema>;

// ---------------------------------------------------------------------------
// API Error Response
// ---------------------------------------------------------------------------

/**
 * Standardized error response shape for all API routes.
 * When fallbackContent is present, the client can render it even on error.
 * This ensures crisis information is always reachable.
 */
export interface ApiErrorResponse {
  readonly error: string;
  readonly code: string;
  readonly fallbackContent?: CrisisContent;
}
