/**
 * Pre-authored, clinician-reviewable crisis response content.
 *
 * This is the single most important file in the entire codebase.
 *
 * SAFETY INVARIANT (SAFETY.md §2.1):
 * - Content in this file is NEVER generated by an LLM at runtime.
 * - It is served directly to users when the risk classifier detects
 *   "possible-overdose" or "self-harm-risk".
 * - The LLM SELECTS which content to serve; it never WRITES crisis guidance.
 *
 * CONTENT SOURCES:
 * - Overdose response steps: adapted from SAMHSA public guidance and
 *   community naloxone-distribution program materials.
 * - Self-harm response: adapted from 988 Suicide & Crisis Lifeline
 *   public-facing guidance.
 * - Hotline numbers: official, verified as of July 2026.
 *
 * @module crisis-static
 */

import type { CrisisContent, HotlineAction } from "../types";

// ---------------------------------------------------------------------------
// Hotline Constants (SAFETY.md §3)
// ---------------------------------------------------------------------------

/** 988 Suicide & Crisis Lifeline — call or text, 24/7. */
export const HOTLINE_988: HotlineAction = {
  type: "tel",
  number: "988",
  label: "988 Suicide & Crisis Lifeline",
} as const;

/** SAMHSA National Helpline — free, 24/7/365 treatment referral. */
export const HOTLINE_SAMHSA: HotlineAction = {
  type: "tel",
  number: "1-800-662-4357",
  label: "SAMHSA National Helpline",
} as const;

/** Emergency services. */
export const HOTLINE_911: HotlineAction = {
  type: "tel",
  number: "911",
  label: "Emergency Services (911)",
} as const;

/** Crisis Text Line — text-based crisis support. */
export const HOTLINE_CRISIS_TEXT: HotlineAction = {
  type: "sms",
  number: "741741",
  label: "Crisis Text Line (text HOME to 741741)",
} as const;

/**
 * All hotlines, ordered by urgency.
 * Rendered as a persistent footer on every screen.
 * Must function with ZERO dependency on the Gemini API. (SAFETY.md §6)
 */
export const ALL_HOTLINES: readonly HotlineAction[] = [
  HOTLINE_911,
  HOTLINE_988,
  HOTLINE_SAMHSA,
  HOTLINE_CRISIS_TEXT,
] as const;

// ---------------------------------------------------------------------------
// Crisis Response Content
// ---------------------------------------------------------------------------

/**
 * Overdose response — served when classifier returns "possible-overdose".
 *
 * Source: SAMHSA "Opioid Overdose Prevention Toolkit" (public domain),
 * community naloxone-distribution program materials.
 *
 * NOTE: This content does NOT provide dosage or administration guidance
 * for any substance. It provides emergency-response steps only.
 */
export const OVERDOSE_RESPONSE: CrisisContent = {
  id: "crisis-overdose",
  title: "If someone may be overdosing",
  body: [
    "Call 911 immediately. Tell them someone may be overdosing.",
    "",
    "While waiting for help:",
    "• Try to keep the person awake and breathing.",
    "• Lay them on their side to prevent choking.",
    "• If you have naloxone (Narcan), use it now.",
    "• Stay with them until help arrives.",
    "",
    "You will not get in trouble for calling for help.",
    "Most states have Good Samaritan laws that protect you.",
  ].join("\n"),
  actions: [HOTLINE_911, HOTLINE_988],
} as const;

/**
 * Self-harm response — served when classifier returns "self-harm-risk".
 *
 * Source: 988 Suicide & Crisis Lifeline public-facing guidance,
 * adapted for text display.
 */
export const SELF_HARM_RESPONSE: CrisisContent = {
  id: "crisis-self-harm",
  title: "You don't have to face this alone",
  body: [
    "What you're feeling right now is real, and it matters.",
    "You deserve support — and trained counselors are available right now.",
    "",
    "Call or text 988 to talk with someone who understands.",
    "They are available 24/7 for substance use, mental health, and crisis support.",
    "",
    "If you are in immediate danger, call 911.",
    "",
    "You are not a burden. Reaching out is a sign of strength.",
  ].join("\n"),
  actions: [HOTLINE_988, HOTLINE_911, HOTLINE_CRISIS_TEXT],
} as const;

/**
 * Generic crisis fallback — served when the system cannot determine
 * the specific crisis type, or as a degraded-mode response when
 * the Gemini API is unreachable.
 */
export const GENERIC_CRISIS_RESPONSE: CrisisContent = {
  id: "crisis-generic",
  title: "Help is available right now",
  body: [
    "If this is a medical emergency, call 911.",
    "",
    "For substance use or mental health support, call or text 988.",
    "The 988 Lifeline is free, confidential, and available 24/7.",
    "",
    "You can also call SAMHSA's National Helpline at 1-800-662-4357",
    "for free treatment referrals and information, 24/7/365.",
  ].join("\n"),
  actions: [HOTLINE_911, HOTLINE_988, HOTLINE_SAMHSA],
} as const;

// ---------------------------------------------------------------------------
// Fallback Script Templates
// ---------------------------------------------------------------------------

/**
 * Fallback script for PIR (Person in Recovery) when the safety filter
 * rejects a generated script. Never returns nothing or raw filtered output.
 */
export const FALLBACK_SCRIPT_PIR = {
  scriptText:
    "Right now, take a slow breath. You've been through hard moments before, " +
    "and you got through them. This feeling is temporary. " +
    "If you need to talk to someone, call 988 — they're available 24/7 " +
    "for substance use support.",
  tone: "gentle" as const,
  citationsUsed: ["988 Suicide & Crisis Lifeline", "SAMHSA"],
};

/**
 * Fallback script for Caregiver when the safety filter rejects a
 * generated script.
 */
export const FALLBACK_SCRIPT_CAREGIVER = {
  scriptText:
    "Take a moment before you respond. What you say right now matters. " +
    "Try: 'I care about you, and I'm here. What do you need from me right now?' " +
    "Avoid ultimatums. If you're unsure what to do, call SAMHSA at 1-800-662-4357.",
  tone: "gentle" as const,
  citationsUsed: ["SAMHSA National Helpline"],
};

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

/**
 * Returns the appropriate crisis content for a given risk tag.
 * Falls back to GENERIC_CRISIS_RESPONSE for unknown tags.
 *
 * @param tag - The risk classification tag
 * @returns Pre-authored crisis content (never generated)
 */
export function getCrisisContentForTag(
  tag: "possible-overdose" | "self-harm-risk" | string
): CrisisContent {
  switch (tag) {
    case "possible-overdose":
      return OVERDOSE_RESPONSE;
    case "self-harm-risk":
      return SELF_HARM_RESPONSE;
    default:
      return GENERIC_CRISIS_RESPONSE;
  }
}
